name: Release Snapshot

on:
  workflow_dispatch:

jobs:
  release-snapshot:
    name: Release Snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Check that the current commit is in main branch
        run: git fetch origin main && git merge-base --is-ancestor $GITHUB_SHA origin/main
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Release with jReleaser
        env:
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_DEPLOY_MAVEN_NEXUS2_SNAPSHOTS_PASSWORD: ${{ secrets.JRELEASER_DEPLOY_MAVEN_NEXUS2_SNAPSHOTS_PASSWORD }}
          JRELEASER_DEPLOY_MAVEN_NEXUS2_SNAPSHOTS_USERNAME: ${{ secrets.JRELEASER_DEPLOY_MAVEN_NEXUS2_SNAPSHOTS_USERNAME }}
        run: ./gradlew publish jreleaserFullRelease --stacktrace -PversionSuffix="-SNAPSHOT"